### ISSUE TITLE
Invalid memory address on run

### ISSUE THREAD

**Issue by avarabyeu** [tockins/realize#100]
go version go1.9.1 darwin/amd64

Command:
```sh 
realize start --name chathook --run
```

Stacktrace:
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x7e088a]

goroutine 53 [running]:
main.(*Project).goRun.func4(0x0, 0xc42009ab00)
	/go/src/github.com/tockins/realize/exec.go:94 +0x3a
panic(0x866880, 0xcc0020)
	/usr/local/go/src/runtime/panic.go:491 +0x283
os/exec.(*Cmd).StdoutPipe(0x0, 0x8fc5f0, 0x0, 0xc42009ab00, 0x0)
	/usr/local/go/src/os/exec/exec.go:609 +0x37
main.(*Project).goRun(0xc42009ab00, 0xc42001a420, 0xc4200490a0)
	/go/src/github.com/tockins/realize/exec.go:103 +0xb23
main.(*Project).routines.func2(0xc42009ab00, 0xc42001a420, 0xc4200490a0)
	/go/src/github.com/tockins/realize/watcher.go:424 +0x128
created by main.(*Project).routines
	/go/src/github.com/tockins/realize/watcher.go:422 +0x1bb
make: *** [Makefile:45: run] Error 2
```

**Comment by avarabyeu** [comment]
Possible reason))))
![Possible reason](https://image.prntscr.com/image/ZwvHn9meTOqN9xa9mYfWzg.png)

**Comment by Asoseil** [comment]
#106

**Comment by Asoseil** [comment]
I re-open it but probably it is already fixed on the branch develop
