### ISSUE TITLE
Realize doesn't play nicely with Emacs interlocking.

### ISSUE THREAD

**Issue by homme** [tockins/realize#164]
Realize crashes whenever Emacs creates an interlock for editing a Go file:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x807598]

goroutine 22 [running]:
github.com/tockins/realize/realize.(*Project).Validate(0xc420164000, 0xc4201cc880, 0x3f, 0x1, 0x0)
        /go/src/github.com/tockins/realize/realize/projects.go:368 +0x498
github.com/tockins/realize/realize.(*Project).Watch(0xc420164000, 0xc420091ad0)
        /go/src/github.com/tockins/realize/realize/projects.go:310 +0x446
created by github.com/tockins/realize/realize.(*Realize).Start
        /go/src/github.com/tockins/realize/realize/cli.go:92 +0xc0
```

Emacs by default creates [interlock files](https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html#Interlocking) to prevent simultaneous editing of a file. These files are symlinks that take the file path of the file being edited but prefix the basename with `.#`. E.g.  editing `/go/src/github.com/FATMAP/rasgen/cmd/rasgen-server/grpclog.go` creates `/go/src/github.com/FATMAP/rasgen/cmd/rasgen-server/.#grpclog.go`. As soon as the interlock file is created realize crashes.

The workaround is to disable interlocking in Emacs but this is less than ideal.

**Comment by conventi** [comment]
One possible solution that could solve this issue is to add a new feature to ignore files that match a regular expression. So we could support a new ignore setting in the yaml config file. This solution aim to be general so it could be useful in many cases and, in the same time, solve this issue.

In this case the regex that define the files that must be ignored could be this `^\.#.*\.go$`.

**Comment by homme** [comment]
That would work for me @conventi. However, a more transparent solution would be for realize to ignore broken symbolic links in the files it matches on, as that is how interlocking is implemented in emacs.  And a broken symbolic link isn't much use to realize anyway I wouldn't have thought?

e.g. 
$ file .#foo.go 

.#foo.go: broken symbolic link to hrz@mapper.30429:1518167384

**Comment by conventi** [comment]
Okay @homme, thanks for the advice! We could add this two features:

1. support regex into config file to ignore the patterns
2. ignore broken symbolic links

**Comment by Asoseil** [comment]
broken symbolic support https://github.com/tockins/realize/commit/13beb532f9a0810a3d8ff2653c96c004f903c4db

**Comment by homme** [comment]
@conventi no problem, thanks for the open mind!  And adding it as two features would be perfect :)

**Comment by mikegleasonjr** [comment]
I'd like to see the regex feature as well, I don't want a modification to my `*_test.go` files to trigger an app reload.
