### ISSUE TITLE
It doesn't work in windows.

### ISSUE THREAD

**Issue by asit-dhal** [tockins/realize#19]
It shows the following error during installation

C:\gowork\medium>go get github.com/tockins/realize
# github.com/tockins/realize/realize
..\..\github.com\tockins\realize\realize\app.go:71: undefined: syscall.Rlimit
..\..\github.com\tockins\realize\realize\app.go:74: undefined: syscall.Setrlimit
..\..\github.com\tockins\realize\realize\app.go:74: undefined: syscall.RLIMIT_NOFILE

**Comment by Asoseil** [comment]
we are working for add the windows support in the next version 1.1

**Comment by erkidhoxholli** [comment]
looking forward to the next version. great job by the way.

**Comment by conventi** [comment]
@erkidhoxholli thanks!

**Comment by TSScrooge** [comment]
WE AREN'T TIRED

**Comment by TSScrooge** [comment]
@conventi no prob

**Comment by arekkas** [comment]
It's now installing, but it's panicing on run:

```
[33m[?[0m22:08:54?[33m]?[0m?[31;1mexec: "C:\\workspace\\go\\src\\....\\services\\api-key-proxy": file does not exist?[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4a51bd]

goroutine 70 [running]:
panic(0x812d80, 0xc0420080b0)
        C:/Go/src/runtime/panic.go:500 +0x1af
os.(*Process).signal(0x0, 0xa4f460, 0xc042008230, 0x0, 0x0)
        C:/Go/src/os/exec_windows.go:58 +0x2d
os.(*Process).Signal(0x0, 0xa4f460, 0xc042008230, 0xc0, 0x99)
        C:/Go/src/os/doc.go:55 +0x46
os.(*Process).kill(0x0, 0xc0420e00c0, 0x0)
        C:/Go/src/os/exec_posix.go:53 +0x4a
os.(*Process).Kill(0x0, 0xa4bfa0, 0xc04202a010)
        C:/Go/src/os/doc.go:40 +0x32
github.com/tockins/realize/watcher.(*Project).goRun.func1(0xc042075080, 0xc0420f21c0, 0xc042101360)
        C:/workspace/go/src/github.com/tockins/realize/watcher/exec.go:43 +0x51
github.com/tockins/realize/watcher.(*Project).goRun(0xc0420f21c0, 0xc042112460, 0xc04216c1c0, 0xc042101360, 0xa4c060, 0xc0420cf900)
        C:/workspace/go/src/github.com/tockins/realize/watcher/exec.go:61 +0x846
created by github.com/tockins/realize/watcher.(*Project).run
        C:/workspace/go/src/github.com/tockins/realize/watcher/watcher.go:110 +0x272


```

**Comment by arekkas** [comment]
Apparently the issue is that `realize add` adds a backwards slash to the config instead of forward:

```
projects:
- name: example
  path: \
```

changing in to a forward slash resolves the panic. However, the build fails because the path is wrong (.exe is missing): 

```
?[33m[?[0m23:25:14?[33m]?[0m?[31mCan't run a not compiled project:?[0m GetFileAttributesEx C:\workspace\go\bin\example: The system cannot find the file specified.
```

**Comment by Asoseil** [comment]
I hope to solve the issue with the next release. i haven't forgotten the windows users (: 
there is also a problem with the colors of the log

**Comment by Asoseil** [comment]
#94 partial solved, need more tests

**Comment by qawarrior** [comment]
it seems to me since GO is a cross platform language that is made for cross compilation that tools should not be a 1.0 if they don't support the core systems.

**Comment by conventi** [comment]
@qawarrior we are working on this.

**Comment by Asoseil** [comment]
tested on win 10, but we need more tests and uses cases.

**Comment by PMLMonteiro** [comment]
Hi.
Running Windows 10 here. 
Can't get realize to install in linux wsl. Neither go get nor go install github.com/oxequa/realize create a binary on my GOPATH.
Any thoughts?
